/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  pikaohjeetSidebar: ['pikaohjeet/alennuksen-lisaaminen', 'pikaohjeet/asiakkaan-haku', 'pikaohjeet/asiakkaan-lisaaminen', 'pikaohjeet/eri-maksaja', 'pikaohjeet/hyvityslasku', 'pikaohjeet/hyvityslasku-poisto', 'pikaohjeet/jakelun-keskeytys', 'pikaohjeet/tilauksen-katkaisu', 'pikaohjeet/katkaisukasittely', 'pikaohjeet/laskun-toimitustapa', 'pikaohjeet/laskun-uudelleenlahetys', 'pikaohjeet/laskutuspyynnon-muokkaus', 'pikaohjeet/maksumuistutus','pikaohjeet/ilmoitusvarauslomake','pikaohjeet/postitus','pikaohjeet/suorituksen-liittaminen', 'pikaohjeet/tilauksen-lisays', 'pikaohjeet/tilausjakson-pidentaminen', 'pikaohjeet/osoitteenmuutos', 'pikaohjeet/tuotteen-hinnanmuutos','pikaohjeet/suorituksen-tiliointi', 'pikaohjeet/valiaikainen-osoitteenmuutos'],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
